# Generated by Django 3.2.15 on 2022-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0166_copy_sla_from_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='disable_openproject_webhook_secret',
            field=models.BooleanField(default=False, help_text='Allows incoming requests without a secret (discouraged legacy behaviour)', verbose_name='Disable web hook secret'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='enable_openproject',
            field=models.BooleanField(default=False, verbose_name='Enable OpenProject integration'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='enable_openproject_web_hook',
            field=models.BooleanField(default=False, help_text='Please note: It is strongly recommended to use a secret below and / or IP whitelist the OpenProject server using a proxy such as Nginx.', verbose_name='Enable OpenProject web hook'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='openproject_minimum_severity',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], default='Low', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='openproject_webhook_secret',
            field=models.CharField(help_text='Secret needed in URL for incoming OpenProject Webhook', max_length=64, null=True, verbose_name='OpenProject Webhook URL'),
        ),
    ]
